// <auto-generated />
using System;
using Eszak_kozephegyseg_kilatoi_GUI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eszak_kozephegyseg_kilatoi_GUI.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240403081859_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Eszak_kozephegyseg_kilatoi_GUI.Location", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Eszak_kozephegyseg_kilatoi_GUI.ViewPoint", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("built")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("height")
                        .HasColumnType("double");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("location")
                        .HasColumnType("int");

                    b.Property<string>("mountain")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("viewpointName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("ViewPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
